### PR TITLE
Fix: Avoid crashes with RCU locks in hypercall logs

### PR DESCRIPTION
**Pull request by AndrewFasano**
Previously we tried fixing part of #11 with #14 which added up/down reads into our `log_mm` method. That didn't seem to work - https://github.com/rehosting/linux/pull/14#issuecomment-2403524780.

This PR changes `log_mm` to instead use RCU so it can read through the `mm->mmap` structure to log VMAs without them changing. It also adds RCU to our context switch logging as testing the first fix at scale revealed that we were also running into invalid pointer accesses with `next->real_parent`.

### CODE REVIEW

**Comment by AndrewFasano** [comment]
With this change I'm still seeing a few non-deterministic errors, ~5 across 250 systems run for 1000s each:

```
[  748.298568] Call Trace:
[  748.299123] [<8023bafc>] log_mm.part.8+0x64/0x1a8
[  748.300146] [<80ce41bc>] __schedule+0x478/0x970
[  748.300770] [<80ce46e0>] schedule+0x2c/0x94
[  748.301359] [<80ce78f0>] schedule_timeout+0x1c4/0x2f0
[  748.302035] [<80165f64>] wait_woken+0x44/0x8c
--
[  133.334469] Call Trace:
[  133.335139] [<80cf9efc>] __schedule+0x428/0x970
[  133.336611] [<80cfa470>] schedule+0x2c/0x94
[  133.337329] [<80481dc0>] fuse_dev_do_read.isra.9.constprop.12+0x204/0x874
[  133.338298] [<80482494>] fuse_dev_read+0x64/0x84
[  133.339038] [<8025d3f0>] __vfs_read+0xe8/0x154
--
[  133.378648] Call Trace:
[  133.378920] [<80cf9efc>] __schedule+0x428/0x970
[  133.379331] [<80cfa470>] schedule+0x2c/0x94
[  133.379737] [<80481dc0>] fuse_dev_do_read.isra.9.constprop.12+0x204/0x874
[  133.380294] [<80482494>] fuse_dev_read+0x64/0x84
[  133.380713] [<8025d3f0>] __vfs_read+0xe8/0x154
--
[  385.058057] Call Trace:
[  385.058541] [<80cf9efc>] __schedule+0x428/0x970
[  385.059352] [<80cfa470>] schedule+0x2c/0x94
[  385.059969] [<8014acd0>] worker_thread+0x21c/0x5e0
[  385.060612] [<80150ef0>] kthread+0x10c/0x13c
[  385.061321] [<80106248>] ret_from_kernel_thread+0x14/0x1c
--
[  818.763806] Call Trace:
[  818.764715] [<80ce416c>] __schedule+0x428/0x970
[  818.766404] [<80ce46e0>] schedule+0x2c/0x94
[  818.767503] [<8026ca34>] pipe_wait+0x70/0xb4
[  818.768591] [<8026d138>] pipe_read+0x1a0/0x350
[  818.769705] [<8025e72c>] __vfs_read+0xe8/0x154
```

**Comment by lacraig2** [comment]
I think the fundamental problem is that we're holding the CPU in this particular code too long. I suspect you're going to continue to run into these errors until we can make this interaction more efficient.

For example: right now we have ~3 hypercalls per memory region in a single `log_mm` call. That can easily be over 100 hypercalls for some processes. 

I'd recommend folding 5911, 5912, 5913, and 5914 into a single hypercall.

I suspect another easy place to make this more efficient is around reading the filenames. This likely needs to be done once per unique region name. Region names are heavily repeated and could be cached for the duration of a report.

**Comment by AndrewFasano** [comment]
While I'm all for optimizations, I don't think that's fundamentally the issue. If we're accessing data in an unsafe way we'll see crashes probabilistically as we scale (assuming the unsafe access just happens to be okay most of the time). If we made it go faster it might be less likely, but I'd expect to still see errors when we run at a large scale.

Since we're 1) customizing the kernel and 2) always running with a single core guest, I'm pretty sure there is a way to do this right and ensure it's safe to read this data.

**Comment by AndrewFasano** [comment]
Superseded by #20

**Pull request closed without merging**
